### Get all posts 
GET http://localhost:3000/post

### Get posts by sender id
GET http://localhost:3000/post?sender=<sender_id>

### Get post by post id
GET http://localhost:3000/post/<post_id>

### Post a new post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "My First Post",
  "content": "post content",
  "sender": "sender_id"
}


### Update post
PUT http://localhost:3000/post/<post_id>
Content-Type: application/json

{
  "title": "Updated post title",
  "content": "Updated post content",
  "sender": "<sender_id>"
}

### Post new comment
POST http://localhost:3000/comment
Content-Type: application/json

{
  "postId": "<post_id>",
  "sender": "<sender_id>",
  "message": "comment!"
}

### Get all comments
GET http://localhost:3000/comment

### Get commetn by id
GET http://localhost:3000/comment/<comment_id>

### Update comment
PUT http://localhost:3000/comment/<comment_id>
Content-Type: application/json

{
  "message": "Updated comment"
}

### Delete comment
DELETE http://localhost:3000/comment/<comment_id>

### Get comments for post
GET http://localhost:3000/comment/post/<comment_id>

